### ISSUE TITLE
download_sra records every 50K of download, big logs ?

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/distiller-nf#118]
![screenshot from 2018-12-12 23-39-19](https://user-images.githubusercontent.com/6790270/49916164-a1890c00-fe67-11e8-929b-b2b0f847bd7e.png)

maybe there is a cli option to turn it off , or `>/dev/null`, or something like that .

most likely not a big deal

**Comment by golobor** [comment]
fixed!

**Comment by golobor** [comment]
fixed!
