### ISSUE TITLE
[Proposal] Genome name in filenames?

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#122]
Maybe we should include genome name in the filenames (or foldernames?) generated by distiller?  @golobor @sergpolly  - what is your take on that? 

It looks like hg19 -> hg38 transition is taking even longer than hg18 -> hg19, suggesting that genome version mixups will keep being an issue. I also noted that many people do not put a genome version in the folder names when they run a dataset.

A reason to have it in the filename is that higlass datastet names will naturally have the genome version in them (assuming the person used filenames as a name).

**Comment by golobor** [comment]
I like this, easy to implement

Anton.
(typed on a phone, sorry for brevity and typos)

**Comment by golobor** [comment]
solved
