### ISSUE TITLE
balance\no balance option 

### ISSUE THREAD

**Issue by azkalot1** [mirnylab/distiller-nf#126]
Setting balance : False in project file passes --no-balance to cooler zoomify. In version 0.8.1 balancing changed, instead of  --no-balance/--balance, there is only --balance option, with balancing off by default. 
It can be fixed with changing 
`def balance_flag = ( params['bin'].get('balance','true').toBoolean() ? "--balance ${balance_options}" : " --no-balance" )`
``
to  `def balance_flag = ( params['bin'].get('balance','true').toBoolean() ? "--balance ${balance_options}" : " " )`

**Comment by sergpolly** [comment]
@azkalot1 would you mind submitting a "Pull Request" with the fix ?
here is a little manual on how to do it without leaving your browser (sorry if it's too obvious or basic - we'll probably use it as a little reference for others who discover bugs and willing to contribute fixes):
1. fork `mirnylab/distiller` - button highlighted:
![fork](https://user-images.githubusercontent.com/6790270/52663966-e23bea80-2ed5-11e9-9b5e-72411bbd09c0.png)
2. edit files in your `fork` to introduce your fix. With such a small change to make - you can even do it online !:
![edit_fork_online](https://user-images.githubusercontent.com/6790270/52664045-0d263e80-2ed6-11e9-960e-90bbc9d46726.png)
3. save/commit your changes - with a short nickname and a reference to this issue in the comment (at the bottom of the page , with the file being edited)
4. submit a "Pull Request" (PR) with your fix; from your `fork` to `mirnylab/distiller-nf/master`:
![submit_pull_request](https://user-images.githubusercontent.com/6790270/52664186-5e363280-2ed6-11e9-83c5-2708e86a8460.png)
5. that's how it would look like after you hit the submit button:
![pr_mirnylab_distiller_master](https://user-images.githubusercontent.com/6790270/52664295-abb29f80-2ed6-11e9-800b-dd5ece79eef6.png)
on the left you should see `mirnylab/distiller->master` on the right your fork/branch - for example `azkalot1/distiller-nf -> master` and right below it - you should see green-colored text ,saying something like "Can automatically merge"; below that you would provide a short nickname for your PR and a small comment referencing this issue; also suggesting reviewers etc.

looking forward to your first contribution!
Thank you!

**Comment by azkalot1** [comment]
pushed pull request

**Comment by golobor** [comment]
many thanks to @azkalot1 for solving this issue!
