### ISSUE TITLE
binning uses config specified decompression command, should use gz-one

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/distiller-nf#131]
as agreed upon a while ago - only internal files are compressed using config-specified compression (lz4,gz, whatever), "final" dedupped pairs are always gz-compressed , gz is more common , than lz4 for instance ...

this code deviates from this convention:
https://github.com/mirnylab/distiller-nf/blob/d72472ff38c7cb1c10081a14fb667e188c0102d4/distiller.nf#L601

even though, upstream stuff https://github.com/mirnylab/distiller-nf/blob/d72472ff38c7cb1c10081a14fb667e188c0102d4/distiller.nf#L561 is a hardcoded gz-compression ...

`lz4` compression option is currently broken

**Comment by golobor** [comment]
solved by @sergpolly
