### ISSUE TITLE
why dropreadID is ignored when makePairsam is False

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/distiller-nf#133]
https://github.com/mirnylab/distiller-nf/blob/d97d6d936d96974f5404415a41f17d15ab5ff6d9/project.yml#L124

just realized - that `dropReadID` is ignored when `makepairsam=False` ...
so all of the `pairs` files have `readids` in them now and files are a lot bigger ... - not good from our perspective ... - merging takes waaaay too long this way.

we should activate the `dropreadID` action for `makepairsam=False ` case as well - to get back to previous default scenario - no `readids`, small `pairs` files .

I'll try to look into that later - will also check what's up with the `dropseq` option.

**Comment by sergpolly** [comment]
looks more like a confusion in the "documentation" ...
https://pairtools.readthedocs.io/en/latest/cli_tools.html#pairtools-parse
according to `pairtools` docs and the code - `--drop-readid` is used for the `.pairs` itself and applied regardless of the `--makepairsam` status.

While `--drop-seq` is indeed drops Phread/sequence from `SAM` field of the `.pairsam` and/or `.sam/bam` output files ....

**Comment by sergpolly** [comment]
tried to address it in  https://github.com/mirnylab/distiller-nf/pull/134

**Comment by golobor** [comment]
thank you @sergpolly for fixing this !

**Comment by sergpolly** [comment]
@golobor do you know why travis is failing to download the sample fastq-s ? it is sad to see this failing tests all the time ...

**Comment by golobor** [comment]
it must be b/c the test data are stored on github, which limits the # of
downloads from a single address - and we're not the only ones to use
travis+github

**Comment by sergpolly** [comment]
so basically we should store the test-case data elsewhere .?
maybe even do `sra` with the `truncate_mode`  ... something like that ?

**Comment by golobor** [comment]
sratools are even less reliable. Storing data elsewhere is a good idea, but
not sure where exactly.
