### ISSUE TITLE
[89/ab2821] NOTE: Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127) -- Execution is retried (1)

### ISSUE THREAD

**Issue by gopel** [mirnylab/distiller-nf#149]
Hi,

Distiller is very interesting for my research, so thank you. However, I stumble upon a weird problem upon running it (cf title). Could someone help me please?

Here is the line I enter in my nextflow repository: $ nextflow run distiller.nf -params-file project.yml 

And here is the full message:
N E X T F L O W  ~  version 20.01.0
Launching `distiller.nf` [gigantic_mercator] - revision: 4b2ff8d377
executor >  local (3)
[-        ] process > download_truncate_chunk_fastqs    -
executor >  local (3)
[-        ] process > download_truncate_chunk_fastqs    -
[-        ] process > local_truncate_chunk_fastqs       -
[-        ] process > fastqc                            -
[25/b975c5] process > map_parse_sort_chunks             [ 67%] 2 of 3, failed: 2, retries: 2
[-        ] process > merge_dedup_splitbam              -
[-        ] process > bin_zoom_library_pairs            -
[-        ] process > merge_zoom_library_group_coolers  -
[-        ] process > merge_stats_libraries_into_groups -
[89/ab2821] NOTE: Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127) -- Execution is retried (1)
[aa/2fc4a3] NOTE: Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127) -- Execution is retried (2)
Error executing process > 'map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)'                                    

executor >  local (3)
[-        ] process > download_truncate_chunk_fastqs    -
[-        ] process > local_truncate_chunk_fastqs       -
[-        ] process > fastqc                            -
[25/b975c5] process > map_parse_sort_chunks             [100%] 3 of 3, failed: 3, retries: 2 ✘
[-        ] process > merge_dedup_splitbam              -
[-        ] process > bin_zoom_library_pairs            -
[-        ] process > merge_zoom_library_group_coolers  -
[-        ] process > merge_stats_libraries_into_groups -
[89/ab2821] NOTE: Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127) -- Execution is retried (1)
[aa/2fc4a3] NOTE: Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127) -- Execution is retried (2)
Error executing process > 'map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)'                                    

executor >  local (3)
[-        ] process > download_truncate_chunk_fastqs    -
[-        ] process > local_truncate_chunk_fastqs       -
[-        ] process > fastqc                            -
[25/b975c5] process > map_parse_sort_chunks             [100%] 3 of 3, failed: 3, retries: 2 ✘
[-        ] process > merge_dedup_splitbam              -
[-        ] process > bin_zoom_library_pairs            -
[-        ] process > merge_zoom_library_group_coolers  -
[-        ] process > merge_stats_libraries_into_groups -
[89/ab2821] NOTE: Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127) -- Execution is retried (1)
[aa/2fc4a3] NOTE: Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127) -- Execution is retried (2)
Error executing process > 'map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)'                                    

Caused by:                                                                                                                           
  Process `map_parse_sort_chunks (library:your_library_name_1 run:lane1 chunk:0)` terminated with an error exit status (127)         

Command executed:                                                                                                                    

  TASK_TMP_DIR=$(mktemp -d -p ./ distiller.tmp.XXXXXXXXXX)
  touch your_library_name_1.lane1.hg38.0.bam 
  bwa mem -t 8  -SP hg38_reference.fasta SRR027958_1.fastq.gz SRR027958_2.fastq.gz         | tee >(samtools view -bS > your_library_name_1.lane1.hg38.0.bam)         | pairtools parse  --drop-readid              --add-columns mapq             -c hg38_chrom_sizes.txt             | pairtools sort --nproc 8                              -o your_library_name_1.lane1.hg38.0.pairsam.gz                              --tmpdir $TASK_TMP_DIR             | cat
  
  rm -rf $TASK_TMP_DIR

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 259: docker: command not found

Work dir:
  /home/biophymember/Projets/HiC_premiere_analyse/essai_nextflow/work/25/b975c5500ab3a684c907871e216052

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

I don't know where the file '.command.sh' is. Here is the content of my folder:
(base)biophymember@rddm503nc:~/Projets/HiC_premiere_analyse/essai_nextflow$ ls bin         
configs       docker           LICENSE          pipeline_info  README.md          test     work CHANGES.md  distiller.nf  environment.yml  nextflow.config  project.yml sorted_chromsizes  VERSION

**Comment by golobor** [comment]
Hi!

(1) the command file mentioned by nextflow can be found in the work folder
(i.e. a temporary folder created for execution of this specific task). In
your case, it must be /home/biophymember/Projets/HiC_premiere_analyse/essai_
nextflow/work/25/b975c5500ab3a684c907871e216052 , as mentioned in the bug
report.

(2) looks like you may not have working docker on your computer, is that
right?

Anton.

**Comment by gopel** [comment]
Hi,

I don’t have Docker, I did not understand it was necessary. I’ll retry on Monday.
Thank you for your help.

Best regards,
Yanis Bendjelal

**Comment by gopel** [comment]
It seems to work, thanks!

**Comment by golobor** [comment]
yay!!!
