### ISSUE TITLE
chunks of fastq.gz not deleted from work folder upon completion of a job 

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#33]

**Comment by sergpolly** [comment]
that's by design I guess ?!

**Comment by golobor** [comment]
the new 'cleanup' feature of nextflow can solve this issue - https://github.com/nextflow-io/nextflow/issues/649

**Comment by golobor** [comment]
closing as a duplicate of  https://github.com/mirnylab/distiller-nf/issues/31
