### ISSUE TITLE
GNU sort uses too much space on /tmp; runs out of space

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#34]
Would be nice to be able to specify where to put temporary files of GNU sort

Error log just in case

[3c/371792] Submitted process > parse_runs (library:WaplKO_1.14-B run:lane2)                                                                                                     [18/1965]
ERROR ~ Error executing process > 'parse_runs (library:WaplKO_3.3-C run:lane1)'

Caused by:
  Process `parse_runs (library:WaplKO_3.3-C run:lane1)` terminated with an error exit status (1)

Command executed:

  mkdir ./tmp4sort
  mkdir ./tmp_pairsam
  parallel -P4 'pairsamtools parse              --drop-seq --drop-readid -c hg19.chrom.sizes.reduced {}             | pairsamtools sort --nproc 4                                 -o ./tmp
_pairsam/{}.pairsam.gz                                 --tmpdir ./tmp4sort ' ::: WaplKO_3.3-C.lane1.20.bam WaplKO_3.3-C.lane1.00.bam WaplKO_3.3-C.lane1.01.bam WaplKO_3.3-C.lane1.03.bam W
aplKO_3.3-C.lane1.02.bam WaplKO_3.3-C.lane1.04.bam WaplKO_3.3-C.lane1.05.bam WaplKO_3.3-C.lane1.43.bam WaplKO_3.3-C.lane1.06.bam WaplKO_3.3-C.lane1.07.bam WaplKO_3.3-C.lane1.08.bam WaplK
O_3.3-C.lane1.09.bam WaplKO_3.3-C.lane1.10.bam WaplKO_3.3-C.lane1.11.bam WaplKO_3.3-C.lane1.12.bam WaplKO_3.3-C.lane1.13.bam WaplKO_3.3-C.lane1.14.bam WaplKO_3.3-C.lane1.15.bam WaplKO_3.
3-C.lane1.17.bam WaplKO_3.3-C.lane1.18.bam WaplKO_3.3-C.lane1.21.bam WaplKO_3.3-C.lane1.19.bam WaplKO_3.3-C.lane1.24.bam WaplKO_3.3-C.lane1.22.bam WaplKO_3.3-C.lane1.23.bam WaplKO_3.3-C.
lane1.27.bam WaplKO_3.3-C.lane1.26.bam WaplKO_3.3-C.lane1.25.bam WaplKO_3.3-C.lane1.29.bam WaplKO_3.3-C.lane1.28.bam WaplKO_3.3-C.lane1.31.bam WaplKO_3.3-C.lane1.30.bam WaplKO_3.3-C.lane
1.32.bam WaplKO_3.3-C.lane1.33.bam WaplKO_3.3-C.lane1.34.bam WaplKO_3.3-C.lane1.35.bam WaplKO_3.3-C.lane1.36.bam WaplKO_3.3-C.lane1.40.bam WaplKO_3.3-C.lane1.41.bam WaplKO_3.3-C.lane1.37
.bam WaplKO_3.3-C.lane1.39.bam WaplKO_3.3-C.lane1.38.bam WaplKO_3.3-C.lane1.42.bam WaplKO_3.3-C.lane1.48.bam WaplKO_3.3-C.lane1.44.bam WaplKO_3.3-C.lane1.45.bam WaplKO_3.3-C.lane1.47.bam
 WaplKO_3.3-C.lane1.46.bam WaplKO_3.3-C.lane1.16.bam
  
  pairsamtools merge ./tmp_pairsam/* --nproc 8 -o WaplKO_3.3-C.lane1.pairsam.gz
  
  rm -rf ./tmp4sort
  rm -rf ./tmp_pairsam
  
  pairsamtools stats WaplKO_3.3-C.lane1.pairsam.gz -o WaplKO_3.3-C.lane1.stats

Command exit status:
  1

Command output:
  (empty)

Command error:
  sort: write failed: /tmp/sortE2aarR: No space left on device
  .command.run.1: line 50: cannot create temp file for here-document: No space left on device
  Traceback (most recent call last):
    File "/miniconda3/bin/pairsamtools", line 11, in <module>
      load_entry_point('pairsamtools==0.0.1.dev0', 'console_scripts', 'pairsamtools')()
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
      rv = self.invoke(ctx)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
      return callback(*args, **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/pairsamtools/pairsam_stats.py", line 50, in stats
      stats_py(input_path, output, merge)
    File "/miniconda3/lib/python3.6/site-packages/pairsamtools/pairsam_stats.py", line 99, in stats_py
      cols[_pairsam_format.COL_C1], 
  IndexError: list index out of range

**Comment by mimakaev** [comment]
It should be logical to put sort temp files in the work directlry perhaps, or wherever all other temp files are created.

**Comment by hakanozadam** [comment]
I had the same problem and the pipeline failed becuase of insufficient space. I ended up providing available space 30x the size of the input.

**Comment by hakanozadam** [comment]
When distiller is running on docker images, it stores the tmp files inside  /var/lib/docker
Inside /var/lib/docker, the intermediate files are stored here: /var/lib/docker/aufs

So, unless we can specify the tmp folder for GNU sort, one needs a lot of space available in the OS volume.

##########################

du -hs /var/lib/*
12K	/var/lib/AccountsService
12K	/var/lib/apparmor
132M	/var/lib/apt
4.0K	/var/lib/dbus
8.0K	/var/lib/dhcp
158G	/var/lib/docker

du -hs /var/lib/docker/aufs
165G	/var/lib/docker/aufs

**Comment by golobor** [comment]
@hakanozadam @sergpolly do you think the issues of space got completely fixed?

**Comment by sergpolly** [comment]
I haven't experienced first hand, so I asked @hakanozadam to check

**Comment by hakanozadam** [comment]
I am still running an earlier version of distiller. But I plan to upgrade to the most recent one soon. Then I can check and provide feedback.

**Comment by golobor** [comment]
this issue is solved, but i'll create a new one for a similar issue
