### ISSUE TITLE
Space Usage

### ISSUE THREAD

**Issue by hakanozadam** [mirnylab/distiller-nf#41]
N GB of input data requires more than 10N space to run. Also, the space usage peaks while doing sort, as mentioned in an earlier ticket. In particular, in my run, 54M of input requires almost 600M of free space to run. Is there any chance to get rid of intermediate files as soon as we delete them?

**Comment by sergpolly** [comment]
related to #52 , at least partially.

@golobor consensus should be reached on the `storeDir` vs `publishDir` and closed

**Comment by golobor** [comment]
mostly solved, now just waiting for a new feature in nextflow
