### ISSUE TITLE
Error at parse_runs step

### ISSUE THREAD

**Issue by hakanozadam** [mirnylab/distiller-nf#42]
I got the following error in parse_runs step. I was able to use the same configuration files on other datasets without any errors but this time it failed after the alignment step.

My map parameters were:
```
map:
    chunksize: 10000000
#    drop_sam: True
    drop_readid: True
    drop_seq: True

####################################

Caused by:
  Cannot invoke method toBoolean() on null object


Source block:
  dropsam_flag = params['map'].get('drop_sam','false').toBoolean() ? '--drop-sam' : ''
  dropreadid_flag = params['map'].get('drop_readid','false').toBoolean() ? '--drop-readid' : ''
  dropseq_flag = params['map'].get('drop_seq','false').toBoolean() ? '--drop-seq' : ''
  stats_command = (params.get('do_stats', 'true').toBoolean() ?
      "pairsamtools stats ${library}.${run}.pairsam.gz -o ${library}.${run}.stats" :
      "touch ${library}.${run}.stats" )
  n_parse_processes = (int)Math.ceil(task.cpus / 2)
  n_parse_processes = n_parse_processes < 1 ? 1 : n_parse_processes
  if( isSingleFile(bam))
      """
      mkdir ./tmp4sort
      pairsamtools parse ${dropsam_flag} ${dropreadid_flag} ${dropseq_flag} \
          -c ${chrom_sizes}  ${bam} \
              | pairsamtools sort --nproc ${task.cpus} \
                                  -o ${library}.${run}.pairsam.gz \
                                  --tmpdir ./tmp4sort \
              | cat
  
      rm -rf ./tmp4sort
  
      ${stats_command}
      """
  else 
      """
      mkdir ./tmp4sort
      mkdir ./tmp_pairsam
      parallel -P${n_parse_processes} 'pairsamtools parse \
          ${dropsam_flag} ${dropseq_flag} ${dropreadid_flag} -c ${chrom_sizes} {} \
          | pairsamtools sort --nproc 4 \
                              -o ./tmp_pairsam/{}.pairsam.gz \
                              --tmpdir ./tmp4sort ' ::: ${bam}
  
      pairsamtools merge ./tmp_pairsam/* --nproc ${task.cpus} -o ${library}.${run}.pairsam.gz

      rm -rf ./tmp4sort
      rm -rf ./tmp_pairsam
  
      ${stats_command}
      """
```
[Nezar: edited formatting]

**Comment by sergpolly** [comment]
That's because parameter `drop_sam` in the `project.yml` is commented, thus it evaluates to `null` by `nextflow`, and `toBoolean(null)` is an error now.


https://github.com/mirnylab/distiller-nf/blob/09a9b41567587384ccb39c76da49f7986f381789/project.yml#L60

All the required parameters are now uncommented in the `project.yml` by default, and should remain as such.

@golobor  this can be closed

**Comment by golobor** [comment]
closing it, but with some extra info:

params['map'].get('drop_sam','false')
uses this get() method: http://docs.groovy-lang.org/docs/groovy-1.7.3/html/groovy-jdk/java/util/Map.html#get(K, V)

the second value is the default value, which is returned when the requested key is missing. Thus, in my understanding, if drop_sam is commented out, it should return 'false', not null. 

Also, I commented out drop_sam and did not get any error, which probably implies that the observed error was in old code and is fixed now.

**Comment by sergpolly** [comment]
I remember the Travis builds were failing when some of the options were commented in `project.yml`, with the same error (`toBoolean(null)`), and uncommenting them were sufficient to fix them.
Some funky docker-related issue maybe?

This could be rediscovered with the next `distiller` commit, one could comment out `drop_sam ` or something like that, and see if Travis would pass

**Comment by golobor** [comment]
i wouldn't blame docker where it could be our issues :) 
anyways, let's see if any similar issue pops up in the future
