### ISSUE TITLE
Problem with Fastqc in Recently Built Docker Image

### ISSUE THREAD

**Issue by hakanozadam** [mirnylab/distiller-nf#49]
We built the docker image after modifying pairsamtools. Everything except for fastqc works fine. Fastqc processes got stuck when we used the new image. Fastqc works in the existing docker image in docker hub.

**Comment by golobor** [comment]
fixed by @nvictus : install ttf-dejavu fonts.
Unfortunately, the fonts are only available via apt, but not via conda. Fixed for now, but in the future it'd be nice to find a way to install via conda.
Will be updated at the next docker image bump.
