### ISSUE TITLE
"Unnecessary" decompression detected 

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/distiller-nf#61]
Not an immediate issue, but rather an observation and something to consider:
processes like `merge_runs_into_libraries` and `merge_chunks_into_runs` are performing `pairsamtools stats` on compressed results of the `merge`. It makes each of the `pairsamtools stats` to decompress "freshly" compressed pairs-file inside the same process. It adds a lot of processing time, at least in the case of `pbgzip` and a slow nodes on a cluster.

Can some kind of clever piping or some other integration save us some cpu cycles here?

**Comment by sergpolly** [comment]
maybe, maybe - statistics gathering can be performed along with parsing ? instead?
We'll end up with `.stat` for each `pairsam` chunk, which can be later merged into runs and libraries as needed

**Comment by sergpolly** [comment]
`merge_runs_into_libraries` does not do the statistics. just to avoid confusion. 

Stats are generated on the level of runs, thus in the `merge_runs_into_libraries ` process, and then stats are merged in a clever way to get stats for `libraries` and `library_groups`

**Comment by sergpolly** [comment]
Mostly addressed with the new `pairsamtools`. Close when the test passes

**Comment by golobor** [comment]
the test passes now, closing
