### ISSUE TITLE
Make option to create zoomified coolers?

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#65]
Will probably add "library_zoomified" and "library_group_zoomified" folders to cooler outputs.

**Comment by sergpolly** [comment]
As in the #45 , we'd need to create zoomified coolers for library and library_group level coolers, right?
Do we still want to control both with a single `params` flag?
Are we going to imply that zoomified coolers have to be balanced, or do we need another `params.flag`? Or probably use the same flag as in #45 to control balancing?
We could simply use the cooler corresponding to the min of `params['bin'].resolutions` to do zoomify, is that ok?
Any particular `--balance-args` we'd want to expose as `params.flag`? Same applies to #45 , actually - we might probably provide them as a single piece `${extra_args_options}` and substitute in `cooler balance ${extra_args_options} -o out.cool in.cool ` and `cooler zoomify --balance --balance-args "${extra_args_options}" -o out.multires.cool  in.hires.cool `.  Does that sound ok?

**Comment by golobor** [comment]
solved by @sergpolly (totally agree with the proposed solution: zoomify both libraries and library_groups, reuse flags from the balancing step)
