### ISSUE TITLE
[enhancement] add new features from cooler

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/distiller-nf#95]
- `cooler` now allows several scenarios when balancing fails https://github.com/mirnylab/cooler/issues/93
we need to incorporate this into `distiller-nf` 
 - `cooler cload pairs` provides access to index-free binning, we should provide a `distiller` option to allow users to bypass `pairix` indexing.

anything else, I'm forgetting ? ...

**Comment by golobor** [comment]
is this one solved, @sergpolly ?

**Comment by sergpolly** [comment]
Looks like it
